### ISSUE TITLE
Add a requirements.txt to help a quick start

### ISSUE THREAD

**Issue by Leslie-William-Zhang** [RaDelft/RaDelft-Dataset#1]
Nice work! I suggest the author add a requirements.txt file to the project. This would help users quickly set up their environment by providing details such as the operating system, PyTorch/Python version, etc.

Additionally, a brief introduction on using the code, particularly the machine_learning_python script, would be helpful. Specifically, it would be great to see instructions on how to perform inference using the downloaded pre-trained networks.

In fact, I acquired a TI cascade radar and have collected some data myself. I'm particularly interested in seeing the output of this amaze networks when fed with my own data.

**Comment by RaDelft** [comment]
Thank you for your suggestion, we are indeed working on this. As you can imagine, all this is voluntary work to share the data and the code to make it available and usable that we do on top of the normal duties. We anticipate to add the requested information soon.

**Comment by IgnacioRoldan** [comment]
Requirements.txt have been added
