### ISSUE TITLE
network.py and network_time.py cannot work

### ISSUE THREAD

**Issue by Leslie-William-Zhang** [RaDelft/RaDelft-Dataset#3]
I try to generate pcs from the tranined NN in network.py or network_time.py by uncomment "generate_point_clouds(params)", and also modify the ["dataset_path"] = "D:/project/RaDelft/dataset/"
 and path ='D:/project/RaDelft/code/machine_learning_python/pre_trained_networks/full_network/epoch=15-step=26208.ckpt'. 

when I run network_time.py, it raise this error:   File "D:\work\anaconda3\envs\mydelft\Lib\site-packages\torch\nn\modules\batchnorm.py", line 536, in _check_input_dim
raise ValueError(f"expected 5D input (got {input.dim()}D input)") ValueError: expected 5D input (got 4D input). 

So I check the problem, in the class "NeuralNetworkRadarDetector", the original input image size is [2, 3, 128, 512, 256], which is 5 dimension. Then, after [image1, image2, image3] = torch.chunk(image, 3, axis=1), the size is [2, 1, 128, 512, 256], then ,after image1 = image1.squeeze(1), the size is [2, 128, 512, 256] which is 4 dimension. Then, image1 = self.DopplerReducer(image1), so let's go back to class "DopplerReducer", this 4 dimension image is fed in self.conv1 = nn.Conv3d(....) first, then fed in self.norm1 = nn.BatchNorm3d(32), the problem is here: BatchNorm3d only accept 5 dimension input (but the input image is 4 dimension, after nn.Conv3d is also 4 dimension)

Also, by the way, the downloaded "pre_trained_networks" has two folders which are "full_network" and "quantile", so what is meaning for them and should applied to which network? since we have network.py, network_nodoppler.py, network_noelevation.py and newwork_time.py

**Comment by BotaoSun** [comment]
Hi, 
To solve the problem that occurred in the _network_time.py_, you could adjust the dimension of **image1** to **[1, channel (2), Doppler (128), Range (512), Azimuth (256)]**. The same process can be executed for **image2/3**

For the network quantile, it means that 10% of the highest value in the power cube and the corresponding elevation value is kept. I think these are just for the ablation studies.

**Comment by Leslie-William-Zhang** [comment]
Many thanks, I just found  change params["bev"] = True to False, then, I don't need to change anything (it means I will not meet the dimension issue I have mentioned). 
However, if params["bev"] = True, I have to adjust the dimension of image 1,2,3 to [1, 2, 128, 512, 256]. But it raised some new problems:  I first  removed "squeeze(1)" and added image1 = image1.permute(1, 0, 2, 3, 4)  image2 = image2.permute(1, 0, 2, 3, 4) image3 = image3.permute(1, 0, 2, 3, 4) so the dimension issue can be solved, but it raise new issues:
"D:\project\RaDelft\code\machine_learning_python\data_preparation\data_preparation.py", line 407, in cube_to_pointcloud
    azimuth_values = azimuth_axis[azimuth_indices]
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
IndexError: index 427 is out of bounds for axis 0 with size 240

**Comment by IgnacioRoldan** [comment]
There was a mistake with the initialization of the 'bev' parameter. In the codes _'network.py'_ and _'network_time.py'_, the parameter should be set to **false**. If you want to run the network without elevation (bev), the code _'network_noElevation.py'_ should be used.

A commit has been made to fix this issue and the new version should work without any changes. In future commits, the 'bev' parameter will be internal, so it can not be modified, thus avoiding errors by changing it.
