### ISSUE TITLE
Timestamps of radar

### ISSUE THREAD

**Issue by Cicio7** [RaDelft/RaDelft-Dataset#5]
Hello! I wonder how you got the timestamps of radar?

**Comment by IgnacioRoldan** [comment]
The TI board used gives an initial timestamp when the capture starts. Then, it generates an extra file (the .idx in the raw data folders) with each frame's timestamp relative to that initial time. For simplicity, I uploaded the timestamps already calculated in absolute time to the data repository instead of the code to generate them from the original .idx files.

**Comment by Cicio7** [comment]
Thank you for your reply! And how can I get the initial timestamp in absolute time?

**Comment by IgnacioRoldan** [comment]
In our dataset, it is the first timestamp in the _timestamps.mat_ files. 

If you want to know how to find it if you are doing measurements with your own TI board, you can look at the generated log at _%mmwave_studio_INSTALL%\mmWaveStudio\RunTime\Trace_*_ and look for the start event.

**Comment by Cicio7** [comment]
<img width="705" alt="屏幕截图 2024-09-26 162607" src="https://github.com/user-attachments/assets/1cf93ca0-8f08-4894-b8ee-f13f0ec8975c">
Which timestamp is the initial timestamp in this file? 16:49:23:699?

**Comment by IgnacioRoldan** [comment]
No, that is when you connect to the board, as it says. It should say start.

**Comment by Cicio7** [comment]
Can you give an example of the timestamp when the capture starts ?

**Comment by Cicio7** [comment]
<img width="815" alt="屏幕截图 2024-09-26 165639" src="https://github.com/user-attachments/assets/14a59dda-5fb5-4ddc-98b0-94f424d045fa">

Could you tell me which timestamp is the initial timestamp in this picture? Thank you very much!

**Comment by IgnacioRoldan** [comment]
You see four start logs because the board has 4 independent chips. I used the start of the first chip as the absolute 0. 

There is a 100 m difference between the first and last logs. If you want to synchronize with other sensors, you will probably have to do an extra calibration step.
