### ISSUE TITLE
Empty bin files in the raw data

### ISSUE THREAD

**Issue by HYY-ying** [RaDelft/RaDelft-Dataset#6]
![image](https://github.com/user-attachments/assets/6bc85f6d-4933-40e5-b0a0-d8d517d92cda)
Hello, why are there empty idx bin files in the raw data folder in the scene 2、4、5、6? Does such a situation affect normal use?

**Comment by IgnacioRoldan** [comment]
Unfortunately, the radar board used is a prototype, and under some unknown conditions, it stops recording data. In some Scenes, you will find that the last 1 or 2 files of the raw data are indeed empty. You will have to skip all these files and the other slaves/master with the same name. In all the results reported these frames have not been used.

**Comment by HYY-ying** [comment]
Ok, thank you very much!
