### ISSUE TITLE
ego-vehicle motion compensation

### ISSUE THREAD

**Issue by HYY-ying** [RaDelft/RaDelft-Dataset#7]
Hello! I want to obtain the velocity of ego-vehicle and compensate the doppler velocity of the radar point clouds. I find that there is velocity information in gps_vel.topic.json, but I can't figure out the coordinate transformation relationship. Transformation matrix in the tf.topic.json doesn't seem to help.

**Comment by BotaoSun** [comment]
> Is there an accurate calibration file between different sensors?

Hi, the calibration between LiDAR and the camera can be referred to:
https://github.com/RaDelft/RaDelft-Dataset/blob/86f5346cbba49e8fc6a879a33158647bf1957f4c/machine_learning_python/visualizers/camera_projection_visualizer.py#L252

The transformation between LiDAR and the radar can be referred to: 
https://github.com/RaDelft/RaDelft-Dataset/blob/86f5346cbba49e8fc6a879a33158647bf1957f4c/machine_learning_python/data_preparation/data_preparation.py#L463

**Comment by HYY-ying** [comment]
Thanks! What about the transformation relationship between radar point cloud and ego-vehicle odometry data in the file gps_odom.topic.json?

**Comment by IgnacioRoldan** [comment]
The transformations between lidar, camera and odometry can be found in the tf.topic.json file. The radar was not recorded with ros, so it is not there. However, to transform from lidar coordinates to radar coordinates you can call the transform_point_cloud function from the data_preparation.py file.

**Comment by HYY-ying** [comment]
But I didn't see the transformations between lidar, camera and odometry in the tf.topic.json file. There are just transformations between base_link coordinate and odom and map coordinate.

**Comment by IgnacioRoldan** [comment]
I just checked with some people who used it, and the data in the odom file and the lidar are in the same coordinate system.

**Comment by HYY-ying** [comment]
So the velocity information in the gps_odom.topic.json and the lidar data don't need to be coordinate transformed. They're in the same coordinate system, right?
